{% set name = "bluesky-live" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bluesky-live-{{ version }}.tar.gz
  sha256: 94f2b71016e9e87f08a901a57145df0bfae5234641c086a001ca463483ae8940

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dask-core >=2
    - entrypoints
    - event-model >=1.16.0
    - numpy
    - pandas
    - python >=3.6
    - xarray

test:
  imports:
    - bluesky_live
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluesky/bluesky-live
  summary: Prototype building blocks for working with streaming data in bluesky
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - danielballan
    - mrakitin
    - stuartcampbell
    - tacaswell
